[package]
name = "rv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
elf = "0.0.12"
gumdrop = "0.8.1"
libc = "0.2.133"
thiserror = "1.0.36"
